language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pyinstaller
  - pyinstaller --onefile hello.py
script:
  - python hello.py
  - ./dist/hello
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - dist/hello
  skip_cleanup: true
  on:
    branch: master
